version: '3.8'

services:
  app:
    build: .
    ports:
      - "2025:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - BASE_URL=${BASE_URL:-https://openrouter.ai/api/v1}
      - MODEL_ID=${MODEL_ID}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: unless-stopped